sudo: required
services:
  - docker

before_install:
  - docker build -t pranjal9599/docker-react -f Dockerfile.dev .

script:
  - docker run pranjal9599/docker-react npm run test -- --coverage

deploy:
  provider: heroku
  app: docker-reac
  api-key: $HEROKU_AUTH_TOKEN
  on:
    branch: master
